title: аккредитованный турагент ведущих судовладельцев России
company: Круиз-Волна
keywords: речные круизы, туры по России, отдых на теплоходе
email: webmaster@rechnoyvokzal.ru
description: >
  аккредитованный турагент ведущих судовладельцев России с 2001 года
baseurl: "/"
bank: >
  ОГРНИП "Круиз-Волна тур” 319508100125923
  ИНН: 501208164028
  р/с 40802810438000168372
  к/с 30101810400000000225
  Московский банк ПАО Сбербанк №9038/01793 г. Москва
  БИК: 044525225
include:
  - _pages
exclude: [LICENSE.txt, README.md]
link: "https://www.cruise-volna.ru"
markdown: kramdown
